sites:
  majorelle_pb:
    name: Majo - PB
    advanced_split: true
    nb_radiologists: 1
    available_weekdays:
    - 0
    - 3
    - 4
    pair_same_day: false
  majorelle_cg:
    name: Majo - CG
    advanced_split: true
    nb_radiologists: 1
    available_weekdays:
    - 2
    - 4
    pair_same_day: false
  majorelle_mb:
    name: Majo - MB
    advanced_split: true
    nb_radiologists: 1
    available_weekdays:
    - 2
    - 4
    pair_same_day: false
  icl:
    name: ICL
    advanced_split: false
    nb_radiologists: 2
    pair_same_day: false
    available_weekdays:
    - 0
    - 1
    - 2
    - 3
    - 4
  radiolor:
    name: Radiolor
    advanced_split: false
    nb_radiologists: 2
    available_weekdays:
    - 0
    - 1
    - 3
    - 4
    pair_same_day: true
  stdizier:
    name: St Dizier
    advanced_split: false
    nb_radiologists: 5
    pair_same_day: false
    available_weekdays:
    - 0
    - 1
    - 2
    - 3
    - 4
  jung:
    name: Jung
    advanced_split: false
    nb_radiologists: 1
    pair_same_day: false
    available_weekdays:
    - 0
    - 1
    - 2
    - 3
    - 4
nb_vacations: 2 # currently not used - todo: implement vacation handling
