majorelle_pb:
  name: 'Majo - PB'
  advanced_split: True
  nb_radiologists: 1
  available_weekdays: [0, 3, 4]
  pair_same_day: False

majorelle_cg:
  name: 'Majo - CG'
  advanced_split: True
  nb_radiologists: 1
  available_weekdays: [2, 4]
  pair_same_day: False

majorelle_mb:
  name: 'Majo - MB'
  advanced_split: True
  nb_radiologists: 1
  available_weekdays: [2, 4]
  pair_same_day: False

icl:
  name: 'ICL'
  advanced_split: False
  nb_radiologists: 3
  pair_same_day: False

radiolor:
  name: 'Radiolor'
  advanced_split: False
  nb_radiologists: 2
  available_weekdays: [0, 1, 3, 4]
  pair_same_day: True

stdizier:
  name: 'St Dizier'
  advanced_split: False
  nb_radiologists: 4
  pair_same_day: False

jung:
  name: 'Jung'
  advanced_split: False
  nb_radiologists: 1
  pair_same_day: False
